using SS.Core;

namespace SS.SectorWar.Callbacks;

// Mirror of asss-ctf's ctf.h custom callbacks. Auto-Register/Unregister methods
// are generated by the SS.Core.CallbackHelperAttribute source generator.

// "freq" scored a point at "enemyFreq" thanks to "scoredBy". score = freq's running total.
[CallbackHelper]
public static partial class CtfScoreCallback
{
    public delegate void CtfScoreDelegate(Arena arena, Player scoredBy, short freq, short enemyFreq, int score);
}

// "p" picked up his own team's flag (returned it home). Original asss-ctf calls this a "save".
[CallbackHelper]
public static partial class CtfSaveCallback
{
    public delegate void CtfSaveDelegate(Arena arena, Player p, short freq);
}

// Game won by "freq". Handlers should add to "points" by ref.
// In our port we expose a closure object (List<int>) instead of `int*`; subscribers
// add to the list and CtfGame sums them. This is the C#-friendly equivalent of
// ASSS's `int* points` out-param convention.
[CallbackHelper]
public static partial class CtfWinCallback
{
    public delegate void CtfWinDelegate(Arena arena, short freq, List<int> points);
}
