using SS.SectorWar.Interfaces;
using SS.Core;
using SS.Core.ComponentInterfaces;
using SS.Packets.Game;

namespace SS.SectorWar.Modules;

// =============================================================================
// SectorWar — Tutorial subsystem (partial-class file).
// =============================================================================
//
// PURPOSE
// -------
// One large map-anchored LVZ poster in the top-left corner of the arena
// showing common commands, gameplay overview, and ship list. Toggled on at
// arena attach, off at detach. No interaction — players fly to it and read.
//
// LVZ POOL
//   - 9500  tutorial_poster.bmp (768x768, generated by
//           tools/lvz_warbird_capital.py:make_tutorial_poster)
//
// MAP POSITION
//   Top-left anchor at pixel (32, 32) — i.e. the poster occupies pixels
//   (32, 32) to (800, 800), which is tiles (2, 2) to (50, 50). This sits in
//   the corner well clear of either team's spawn (~tile 256/768 on the X
//   axis) so it never overlaps live combat space.
//
// RUNTIME OWNERSHIP
//   - Owned state: NONE (single static slot, position set once at attach).
//   - Conf keys read: NONE.
//   - Persisted data: NONE.
//   - Fakes registered: NONE.
//   - Timers: NONE.
//   - Broker interfaces published: NONE.
//
// THREADING: mainloop only.
// =============================================================================

public sealed partial class SectorWar
{
    /// <summary>LVZ objects reserved by tools/lvz_warbird_capital.py.
    /// Slot A = Quick Start poster (Commands / Gameplay / How To Win).
    /// Slot B = Combat &amp; Defense poster (HQ Anatomy / Deployables /
    /// Inventory + Ships). Both 768x768.</summary>
    private const short TutorialPosterSlotA = 9500;
    private const short TutorialPosterSlotB = 9501;

    /// <summary>Pixel anchors. Poster A at (32, 32) → tiles (2, 2)..(50, 50).
    /// Poster B at (832, 32) → tiles (52, 2)..(100, 50). Together they
    /// span 1568 px along the top of the map — well clear of both team
    /// spawns (~tile 256 / 768 on the X axis).</summary>
    private const short TutorialPosterAnchorX_A = 32;
    private const short TutorialPosterAnchorX_B = 832;
    private const short TutorialPosterAnchorY = 32;

    private void LoadTutorial(IComponentBroker broker)
    {
        _logManager.LogM(LogLevel.Info, LogCategory, "Tutorial subsystem loaded.");
    }

    private void UnloadTutorial(IComponentBroker broker) { /* no zone-wide state */ }

    private void AttachTutorial(Arena arena)
    {
        try
        {
            _lvzObjects.SetPosition(arena, TutorialPosterSlotA,
                TutorialPosterAnchorX_A, TutorialPosterAnchorY,
                ScreenOffset.Normal, ScreenOffset.Normal);
            _lvzObjects.Toggle(arena, TutorialPosterSlotA, true);

            _lvzObjects.SetPosition(arena, TutorialPosterSlotB,
                TutorialPosterAnchorX_B, TutorialPosterAnchorY,
                ScreenOffset.Normal, ScreenOffset.Normal);
            _lvzObjects.Toggle(arena, TutorialPosterSlotB, true);
        }
        catch (Exception ex)
        {
            _logManager.LogA(LogLevel.Warn, LogCategory, arena,
                $"Tutorial poster attach failed: {ex.Message}");
        }
    }

    private void DetachTutorial(Arena arena)
    {
        try { _lvzObjects.Toggle(arena, TutorialPosterSlotA, false); }
        catch { /* phong's no-crash rule */ }
        try { _lvzObjects.Toggle(arena, TutorialPosterSlotB, false); }
        catch { /* phong's no-crash rule */ }
    }
}
