using SS.SectorWar.Interfaces;
using SS.Core;
using SS.Core.ComponentInterfaces;
using SS.Packets.Game;

namespace SS.SectorWar.Modules;

// =============================================================================
// SectorWar — Tutorial subsystem (partial-class file).
// =============================================================================
//
// PURPOSE
// -------
// One large map-anchored LVZ poster in the top-left corner of the arena
// showing common commands, gameplay overview, and ship list. Toggled on at
// arena attach, off at detach. No interaction — players fly to it and read.
//
// LVZ POOL
//   - 9500  tutorial_poster.bmp (768x768, generated by
//           tools/lvz_warbird_capital.py:make_tutorial_poster)
//
// MAP POSITION
//   Top-left anchor at pixel (32, 32) — i.e. the poster occupies pixels
//   (32, 32) to (800, 800), which is tiles (2, 2) to (50, 50). This sits in
//   the corner well clear of either team's spawn (~tile 256/768 on the X
//   axis) so it never overlaps live combat space.
//
// RUNTIME OWNERSHIP
//   - Owned state: NONE (single static slot, position set once at attach).
//   - Conf keys read: NONE.
//   - Persisted data: NONE.
//   - Fakes registered: NONE.
//   - Timers: NONE.
//   - Broker interfaces published: NONE.
//
// THREADING: mainloop only.
// =============================================================================

public sealed partial class SectorWar
{
    /// <summary>LVZ object reserved by tools/lvz_warbird_capital.py.</summary>
    private const short TutorialPosterSlot = 9500;

    /// <summary>Top-left pixel anchor for the 768x768 poster. Sits in tiles
    /// (2, 2) to (50, 50) — well away from either team's spawn.</summary>
    private const short TutorialPosterAnchorX = 32;
    private const short TutorialPosterAnchorY = 32;

    private void LoadTutorial(IComponentBroker broker)
    {
        _logManager.LogM(LogLevel.Info, LogCategory, "Tutorial subsystem loaded.");
    }

    private void UnloadTutorial(IComponentBroker broker) { /* no zone-wide state */ }

    private void AttachTutorial(Arena arena)
    {
        try
        {
            _lvzObjects.SetPosition(arena, TutorialPosterSlot,
                TutorialPosterAnchorX, TutorialPosterAnchorY,
                ScreenOffset.Normal, ScreenOffset.Normal);
            _lvzObjects.Toggle(arena, TutorialPosterSlot, true);
        }
        catch (Exception ex)
        {
            _logManager.LogA(LogLevel.Warn, LogCategory, arena,
                $"Tutorial poster attach failed: {ex.Message}");
        }
    }

    private void DetachTutorial(Arena arena)
    {
        try { _lvzObjects.Toggle(arena, TutorialPosterSlot, false); }
        catch { /* phong's no-crash rule */ }
    }
}
